### ISSUE TITLE
Cloudant Warehouse Create warehouse option not available ? 

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant-labs/data-flow-examples#16]
" Create warehouse option is not available," I think after depreciation this option has been removed.
what is an alternative option available to create a warehouse with Cloudant?
![image](https://user-images.githubusercontent.com/11150958/38539146-50f62670-3cb0-11e8-9df4-6289b94973cf.png)

**Comment by ricellis** [comment]
Correct, the warehouse is being deprecated and removed according to that timeline. This repository provides a number of options for copying data from Cloudant to Db2 Warehouse on Cloud using various IBM Cloud solutions. [Use the tutorials in this repository](https://github.com/cloudant-labs/data-flow-examples#examples-to-ibm-db2-warehouse-on-cloud) to get started using the technology you prefer, but you'll need to customize the example solutions to your specific requirements as stated in the README.

**Comment by ZaheerUdDeen** [comment]
Can I automatically trigger python script after changes have been made in cloudant?
