### ISSUE TITLE
How can I recover deleted document from cloudant database ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant-labs/data-flow-examples#17]

**Comment by ZaheerUdDeen** [comment]
I want to recover the last deleted document. The below option shows how many deleted but is there any option to recover the last deleted document?
![image](https://user-images.githubusercontent.com/11150958/38539859-443af4b2-3cb3-11e8-94c2-c4f8c4ea33c8.png)

**Comment by ricellis** [comment]
This is nothing to do with this data-flow-examples repository, I suggest you contact Cloudant support.
