### ISSUE TITLE
How to automatically trigger python script after changes made in  cloudant ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant-labs/data-flow-examples#18]

**Comment by ricellis** [comment]
Python is an available environment in IBM Cloud Functions. The [Cloud Functions tutorial](https://github.com/cloudant-labs/data-flow-examples/blob/master/cloud-functions/README.md) demonstrates the Cloudant changes trigger coupled to a Node.js action, but the action could be replaced with Python instead.

Alternatively the [Streams Designer tutorial](https://github.com/cloudant-labs/data-flow-examples/blob/master/streams-designer/README.md) has example python-cloudant code for listening to the changes feed.
