### ISSUE TITLE
How to make custom table in Cloudant to Db2 in Spark using Watson Studio ?

### ISSUE THREAD

**Issue by ZaheerUdDeen** [cloudant-labs/data-flow-examples#20]
I want to make a table in Db2 warehouse for the give (document screenShot) in Spark using Watson studio.
![image](https://user-images.githubusercontent.com/11150958/38600172-a20f2058-3d7c-11e8-9c83-b1eac87b9185.png)
The table cloumn name should be the content(invNumber,salePrice..) json object in 'totalInvoice' JsonArray.

Secondly:
   If I want to do the same job with node-red how can I do that?

**Comment by ricellis** [comment]
i) Spark
Unpacking arrays and objects with Spark is [documented in this example](https://github.com/cloudant-labs/data-flow-examples/blob/master/spark-on-watson-studio/json-array-object-to-db2-data-type.md). Further the [`SaveMode` options available for Spark to `CREATE TABLE` are also documented](https://github.com/cloudant-labs/data-flow-examples/blob/master/warehousing-alternatives-compare-table.md#sink-options-to-db2).

ii) Node-RED
It is stated in this [repository's documentation that Node-RED has only an `INSERT` statement for the Db2 sink](https://github.com/cloudant-labs/data-flow-examples/blob/master/warehousing-alternatives-compare-table.md#sink-options-to-db2).
If you want to do more complicated actions, like `CREATE TABLE` you'll want to find and install or create some other Node-RED nodes. That is outside of the scope of what we've done here and we can't provide help with that.

Please only raise issues here if you find a bug when working through the tutorials. Cloudant are unable to provide support for all the IBM Cloud services used in these tutorials.
