### ISSUE TITLE
Cloudant_to_Db2_streams_flow.stp

### ISSUE THREAD

**Issue by saba-in** [cloudant-labs/data-flow-examples#27]
Could you please guide the purpose of .stp file format and from where it is generated.

**Comment by emlaver** [comment]
@saba-in this file was generated from IBM Watson Studio's Streams Flow service.  In the [IBM Streams Designer tutorial](https://github.com/cloudant-labs/data-flow-examples/tree/master/streams-designer#simple-load-from-cloudant-to-db2-in-streams-designer), there are two options:
1) Import the provided .stp Streams flow file
2) Create the streams flow manually

**Comment by saba-in** [comment]
@emlaver Thank you, it worked! The tutorial have been very useful
